// This file was autogenerated by calcdeps.py
goog.addDependency("../../../Web-SDK/src/0_config.js", ['config'], []);
goog.addDependency("../../../Web-SDK/src/0_utils.js", ['utils'], []);
goog.addDependency("../../../Web-SDK/src/1_api.js", ['api'], ['config', 'utils']);
goog.addDependency("../../../Web-SDK/src/1_resources.js", ['resources'], ['utils', 'config']);
goog.addDependency("../../../Web-SDK/src/2_branch.js", ['Branch'], ['utils', 'resources', 'api']);
goog.addDependency("../../../Web-SDK/src/2_branch_tests.js", [], ['Branch', 'goog.testing.AsyncTestCase', 'goog.testing.jsunit']);
goog.addDependency("../../../Web-SDK/src/3_branch_instance.js", ['branch_instance'], ['Branch']);
goog.addDependency("../../../Web-SDK/src/4_umd.js", [], ['branch_instance']);
goog.addDependency("../../../Web-SDK/tests/branch-deps.js", [], []);
goog.addDependency("../../../Web-SDK/src/extern.js", [], []);
goog.addDependency("../../../Web-SDK/src/onpage.js", [], []);
