// jscs:disable
// This file was autogenerated by calcdeps.py
goog.addDependency("../../../../../src/0_banner_utils.js", ['banner_utils'], ['utils', 'storage']);
goog.addDependency("../../../../../src/0_config.js", ['config'], []);
goog.addDependency("../../../../../src/0_queue.js", ['Queue'], []);
goog.addDependency("../../../../../src/0_storage.js", ['storage'], []);
goog.addDependency("../../../../../src/0_utils.js", ['utils'], ['goog.json', 'storage']);
goog.addDependency("../../../../../src/1_api.js", ['Server'], ['utils', 'goog.json', 'storage']);
goog.addDependency("../../../../../src/1_banner_css.js", ['banner_css'], ['banner_utils']);
goog.addDependency("../../../../../src/1_banner_html.js", ['banner_html'], ['banner_utils', 'utils', 'storage']);
goog.addDependency("../../../../../src/1_resources.js", ['resources'], ['utils', 'config']);
goog.addDependency("../../../../../src/2_banner.js", ['banner'], ['banner_utils', 'banner_css', 'banner_html', 'config', 'utils']);
goog.addDependency("../../../../../src/3_branch.js", ['Branch'], ['utils', 'resources', 'Server', 'banner', 'Queue', 'storage', 'config', 'goog.json']);
goog.addDependency("../../../../../src/4_initialization.js", ['branch_instance'], ['Branch']);
goog.addDependency("../../../../../src/extern.js", [], []);
goog.addDependency("../../../../../src/onpage.js", [], []);
goog.addDependency("../../../../../tests/0_queue.js", [], ['Queue']);
goog.addDependency("../../../../../tests/0_storage.js", [], ['storage']);
goog.addDependency("../../../../../tests/0_utils.js", [], ['utils']);
goog.addDependency("../../../../../tests/1_api.js", [], ['utils', 'Server', 'resources', 'config', 'storage']);
goog.addDependency("../../../../../tests/3_branch.js", [], ['utils', 'Branch', 'resources', 'config', 'storage', 'goog.json']);
goog.addDependency("../../../../../tests/4_integration.js", [], ['utils', 'Server', 'Queue', 'Branch', 'resources', 'config', 'storage', 'goog.json']);
goog.addDependency("../../../../../tests/test-utils.js", [], []);
